# Hardware configuration for desktop machine
# This file was originally generated by 'nixos-generate-config'
# and contains hardware-specific settings.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Kernel modules for hardware support
  boot = {
    initrd = {
      # Available kernel modules
      availableKernelModules = [
        "xhci_pci"    # USB 3.0 support
        "ahci"        # SATA support
        "nvme"        # NVMe drive support
        "usbhid"      # USB HID devices
        "usb_storage" # USB storage devices
        "sd_mod"      # SD card support
        "sr_mod"      # CD/DVD drive support
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];  # Intel KVM support
    extraModulePackages = [ ];
  };

  # Filesystem configuration
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/e1d47fb4-3823-4c05-bb54-bfb254672fb0";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/C9D6-937D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  };

  # Swap configuration
  swapDevices = [
    { device = "/dev/disk/by-uuid/c7fbdb84-4db6-46ba-ba81-441e212450bd"; }
  ];

  # Network configuration
  # Using DHCP by default for all interfaces
  networking.useDHCP = lib.mkDefault true;

  # Platform and CPU configuration
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}