set-option -g mouse on
bind-key M if-shell -F '#{mouse}' \
  'set-option -g mouse off' \
  'set-option -g mouse on'

set-option -g default-shell /run/current-system/sw/bin/bash
set-option -g default-command /run/current-system/sw/bin/fish
set-option -g status off
set-option -g pane-border-status off

unbind-key C-b
set-option -g prefix C-g
bind-key C-g send-prefix

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'
set-window-option -g @tabby_color transparent
set-window-option -g @tabby_name_locked 1
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'brendandebeasi/tabby'

if-shell "test ! -d ~/.config/tmux/plugins/tpm" \
  "run-shell 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

if-shell "test -d ~/.config/tmux/plugins/tabby && test ! -x ~/.config/tmux/plugins/tabby/bin/tabby" \
  "run-shell 'cd ~/.config/tmux/plugins/tabby && ./scripts/install.sh'"

run-shell '~/.config/tmux/plugins/tpm/tpm'
run-shell -b 'sleep 1; tmux set-option -g pane-border-status off; tmux refresh-client -S'
