# customCommands:
#   - key: "C"
#     command: "git cz"
#     description: "commit with commitizen"
#     context: "files"
#     loadingText: "opening commitizen commit tool"
#     subprocess: true

gui:
  language: "ja"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
