name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # 毎週日曜日の午前0時に実行
jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      pull-request-number: ${{ steps.update.outputs.pull-request-number }}
      pull-request-url: ${{ steps.update.outputs.pull-request-url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            trusted-public-keys = hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hyprland.cachix.org https://cache.nixos.org/
      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          inputs: nixpkgs nixos-hardware home-manager nix-darwin hyprland catppuccin zen-browser treefmt-nix
          pr-title: "chore: Update flake.lock"
          pr-labels: |
            dependencies
            automated
  check-and-merge:
    needs: update-lockfile
    if: needs.update-lockfile.outputs.pull-request-number != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: refs/heads/update_flake_lock_action
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            trusted-public-keys = hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hyprland.cachix.org https://cache.nixos.org/
      - name: Run Nix Flake check
        run: nix flake check
      - name: Eval NixOS configuration # Build すると GitHub ホステッドランナーのストレージを使い果たしてしまうっぽいのでしかたない
        run: nix eval .#nixosConfigurations.hikuo-desktop.config.system.build.toplevel --raw
      - name: Eval Home-Manager configuration
        run: nix eval .#homeConfigurations.hikuo.activationPackage --raw
      - name: Auto-merge if checks pass
        if: success()
        run: |
          gh pr merge "${{ needs.update-lockfile.outputs.pull-request-number }}" \
            --auto \
            --merge \
            --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on failure
        if: failure()
        run: |
          gh pr comment "${{ needs.update-lockfile.outputs.pull-request-number }}" \
            --body "@hikuohiku ビルドチェックが失敗しました。手動での確認が必要です。"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
