name: Auto Rebase Host-Specific Branches

on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: write

jobs:
  get-hosts:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.set-hosts.outputs.hosts }}
    steps:
      - name: Set host list
        id: set-hosts
        run: |
          # ホスト一覧をJSON配列として定義
          echo "hosts=[\"hikuo-macbook\", \"hikuo-desktop\"]" >> $GITHUB_OUTPUT
  rebase-host-branches:
    needs: get-hosts
    runs-on: ubuntu-latest
    strategy:
      # 1つのブランチの失敗が他のブランチのリベースを妨げないようにする
      fail-fast: false
      matrix:
        host: ${{ fromJson(needs.get-hosts.outputs.hosts) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Rebase host branch
        run: |
          BRANCH="${{ matrix.host }}"
          echo "Processing branch: $BRANCH"

          # ブランチの存在確認
          if ! git fetch origin "$BRANCH:$BRANCH"; then
            echo "::error::Branch $BRANCH does not exist or could not be fetched"
            exit 1
          fi

          # ブランチの切り替え
          if ! git checkout "$BRANCH"; then
            echo "::error::Failed to checkout branch $BRANCH"
            exit 1
          fi

          # リベースの実行
          if ! git rebase origin/main; then
            echo "::error::Rebase failed for branch $BRANCH. There might be conflicts that need manual resolution"
            git rebase --abort
            exit 1
          fi

          # プッシュの実行
          if ! git push --force-with-lease origin "$BRANCH"; then
            echo "::error::Push failed for branch $BRANCH - Remote branch has diverged from our last fetched state. Someone else might have pushed changes to this branch"
            exit 1
          fi

          echo "::notice::Successfully rebased and pushed branch $BRANCH"
